export const dummyTodo = {
    userName: '그로우업',
    time: '123:30:18',
    todo: [['예시입니다예시입니다예시입니다예시입니다예시입니다',true],
    ['저거도 할거임',false],
    ['예시입니다예시입니다예시예시인닝리나디러인ㄹ',false]]
  };


export const dummyEvents = [
  {
    date: new Date(2024, 0, 1),
    text: '새해 첫날, 이것도하고, 저것도하고, 이것도 하고, 저것도하고,',
    backgroundColor: '#FFE5E5',
  },
  {
    date: new Date(2024, 0, 5),
    text: '친구와 저녁 약속, React 학습하기',
    backgroundColor: '#EFECFF',
  },
  {
    date: new Date(2024, 0, 10),
    text: '책 읽기 모임',
    backgroundColor: '#FFF',
  },
  {
    date: new Date(2024, 0, 15),
    text: '영화 보기',
    backgroundColor: '#FFF',
  },
  {
    date: new Date(2024, 0, 20),
    text: '월간 목표 회의',
    backgroundColor: '#EFECFF',
  },
  {
    date: new Date(2024, 0, 25),
    text: '디자인 스터디 참여',
    backgroundColor: '#FFF7CA',
  },
  {
    date: new Date(2024, 0, 30),
    text: '블로그 글 작성하기',
    backgroundColor: '#FFE5E5',
  },

];


export const dummyData = [
  {
    deadline: "2023.12.05",
    maintext: "이제 막 공부 시작한 디자이너와 프론트엔드 개발자를 구합니다! 어서 오세요요용",
    views: 1500,
    status: "open", //close or open
    like: "like", //like or unlike
    popular: true, //인기태그 표시 여부
    study: true, //스터디 태그 표시 여부
  },
  {
    deadline: "2023.12.05",
    maintext: "예시글입니다예시글입니다아아아아아안녕하세요모집합니다구합니다",
    views: 143,
    status: "close",
    like: "like",
    popular: true,
    study: false, 
  },
  {
    deadline: "2023.12.05",
    maintext: "범위초과시 ...으로표시합니다",
    views: 12,
    status: "close",
    like: "unlike",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "dummy data 현재 활용중입니다 이후 api 연결시 dummy 지움",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "5번째글입니다 안녕하세요안녕하세요안녕하세요",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "pagenation test용 더미데이터입니다입니다입입니다다다",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "page가 이까지 넘어오나요?",
    views: 998,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
];