export const dummyRanking = [
  {
    "rank": 1,
    "name": "유영천",
    "time": "1252:65:25"
  },
  {
    "rank": 2,
    "name": "윤다희",
    "time": "1152:60:20"
  },
  {
    "rank": 3,
    "name": "박수진",
    "time": "1100:58:30"
  },
  {
    "rank": 4,
    "name": "오아영",
    "time": "1020:50:20"
  },
  {
    "rank": 5,
    "name": "방지원",
    "time": "950:45:15"
  },
  {
    "rank": 6,
    "name": "김민찬",
    "time": "900:40:10"
  },
  {
    "rank": 7,
    "name": "김더미",
    "time": "850:35:5"
  },
  {
    "rank": 8,
    "name": "박바보",
    "time": "800:30:0"
  },
  {
    "rank": 9,
    "name": "정성실",
    "time": "750:25:55"
  },
  {
    "rank": 10,
    "name": "아무개",
    "time": "700:20:50"
  }
]

export const dummyLiveUpPost = [
  {
    deadline: "2023.12.25",
    maintext: "초보자들 모여라! 🚀 Python 스터디 오픈! 기초부터 고수가 되기까지 함께해요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.31",
    maintext: "데이터 사이언스에 빠져봐요! 📊 함께하는 데이터 사이언스 스터디 모집 중! 👩‍💻👨‍💻",
    views: 550,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.05",
    maintext: "디자인 강좌에 눈 돌려봐요! 🎨 웹 디자인 스터디 오픈! 더 나은 UX를 만들기 위해 함께 노력해요!",
    views: 800,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2024.01.10",
    maintext: "글쓰기에 자신 있는 사람 모집! ✍ 글쓰기 스터디에서 함께 발전해요!",
    views: 1100,
    status: "close",
    like: "like",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.15",
    maintext: "코딩 파티에 초대합니다! 💻 프로그래밍 스터디에서 코딩의 신세계를 열어봐요!",
    views: 700,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.20",
    maintext: "영상 편집 매니아 여러분! 🎬 영상 편집 스터디 참여하실 분 구합니다. 함께 기술 향상하세요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "디자인 초보자와 함께 공부하는 그룹을 만들어요! 함께 성장해 나가실 분을 찾습니다. 오세요오세요!",
    views: 1500,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "예시 글입니다. 어서와서 같이 코딩 공부합시다! 모집 중입니다. 참여해 주세요.",
    views: 143,
    status: "close",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.06",
    maintext: "프론트엔드 개발 초보자와 함께하는 스터디를 시작합니다. 경력자도 환영합니다!",
    views: 800,
    status: "open",
    like: "unlike",
    popular: false,
    study: false,
  },
  {
    deadline: "2023.12.10",
    maintext: "UI/UX 디자인 스터디 모집합니다. 함께 디자인 실력을 키워봐요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.15",
    maintext: "백엔드 개발자와 함께하는 스터디를 시작합니다. 함께 공부하며 실력을 향상시켜요!",
    views: 600,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2023.12.20",
    maintext: "웹 디자인 초보자와 함께하는 모임입니다. 함께 디자인을 배우고 발전해봐요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.25",
    maintext: "🎉 파이썬 입문자를 환영합니다! 함께하는 Python 초보자 그룹에서 즐거운 학습을 시작해봐요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.31",
    maintext: "🚀 데이터 사이언스 여행에 함께 떠나볼래요? 데이터 분석과 머신러닝을 다루는 스터디를 엽니다!",
    views: 550,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.05",
    maintext: "💡 디자인의 마법에 빠져봐요! UX 디자인 스터디에서 창의적인 디자인을 함께 연마해봐요!",
    views: 800,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2024.01.10",
    maintext: "📝 글쓰기의 기술을 향상시켜보세요! 글쓰기 스터디에서 효과적인 표현력을 함께 키워나갑시다!",
    views: 1100,
    status: "close",
    like: "like",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.15",
    maintext: "💻 코드의 세계로 초대합니다! 프로그래밍 스터디에서 함께 코딩의 매력을 발견해봐요!",
    views: 700,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.20",
    maintext: "🎬 영상 편집의 신세계를 경험하세요! 영상 편집 스터디에서 창의적인 비디오 제작을 배워봐요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.25",
    maintext: "초보자들 모여라! 🚀 Python 스터디 오픈! 기초부터 고수가 되기까지 함께해요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.31",
    maintext: "데이터 사이언스에 빠져봐요! 📊 함께하는 데이터 사이언스 스터디 모집 중! 👩‍💻👨‍💻",
    views: 550,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.05",
    maintext: "디자인 강좌에 눈 돌려봐요! 🎨 웹 디자인 스터디 오픈! 더 나은 UX를 만들기 위해 함께 노력해요!",
    views: 800,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2024.01.10",
    maintext: "글쓰기에 자신 있는 사람 모집! ✍ 글쓰기 스터디에서 함께 발전해요!",
    views: 1100,
    status: "close",
    like: "like",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.15",
    maintext: "코딩 파티에 초대합니다! 💻 프로그래밍 스터디에서 코딩의 신세계를 열어봐요!",
    views: 700,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.20",
    maintext: "영상 편집 매니아 여러분! 🎬 영상 편집 스터디 참여하실 분 구합니다. 함께 기술 향상하세요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "디자인 초보자와 함께 공부하는 그룹을 만들어요! 함께 성장해 나가실 분을 찾습니다. 오세요오세요!",
    views: 1500,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "예시 글입니다. 어서와서 같이 코딩 공부합시다! 모집 중입니다. 참여해 주세요.",
    views: 143,
    status: "close",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.06",
    maintext: "프론트엔드 개발 초보자와 함께하는 스터디를 시작합니다. 경력자도 환영합니다!",
    views: 800,
    status: "open",
    like: "unlike",
    popular: false,
    study: false,
  },
  {
    deadline: "2023.12.10",
    maintext: "UI/UX 디자인 스터디 모집합니다. 함께 디자인 실력을 키워봐요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.15",
    maintext: "백엔드 개발자와 함께하는 스터디를 시작합니다. 함께 공부하며 실력을 향상시켜요!",
    views: 600,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2023.12.20",
    maintext: "웹 디자인 초보자와 함께하는 모임입니다. 함께 디자인을 배우고 발전해봐요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.25",
    maintext: "🎉 파이썬 입문자를 환영합니다! 함께하는 Python 초보자 그룹에서 즐거운 학습을 시작해봐요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.31",
    maintext: "🚀 데이터 사이언스 여행에 함께 떠나볼래요? 데이터 분석과 머신러닝을 다루는 스터디를 엽니다!",
    views: 550,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.05",
    maintext: "💡 디자인의 마법에 빠져봐요! UX 디자인 스터디에서 창의적인 디자인을 함께 연마해봐요!",
    views: 800,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2024.01.10",
    maintext: "📝 글쓰기의 기술을 향상시켜보세요! 글쓰기 스터디에서 효과적인 표현력을 함께 키워나갑시다!",
    views: 1100,
    status: "close",
    like: "like",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.15",
    maintext: "💻 코드의 세계로 초대합니다! 프로그래밍 스터디에서 함께 코딩의 매력을 발견해봐요!",
    views: 700,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.20",
    maintext: "🎬 영상 편집의 신세계를 경험하세요! 영상 편집 스터디에서 창의적인 비디오 제작을 배워봐요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.25",
    maintext: "초보자들 모여라! 🚀 Python 스터디 오픈! 기초부터 고수가 되기까지 함께해요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.31",
    maintext: "데이터 사이언스에 빠져봐요! 📊 함께하는 데이터 사이언스 스터디 모집 중! 👩‍💻👨‍💻",
    views: 550,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.05",
    maintext: "디자인 강좌에 눈 돌려봐요! 🎨 웹 디자인 스터디 오픈! 더 나은 UX를 만들기 위해 함께 노력해요!",
    views: 800,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2024.01.10",
    maintext: "글쓰기에 자신 있는 사람 모집! ✍ 글쓰기 스터디에서 함께 발전해요!",
    views: 1100,
    status: "close",
    like: "like",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.15",
    maintext: "코딩 파티에 초대합니다! 💻 프로그래밍 스터디에서 코딩의 신세계를 열어봐요!",
    views: 700,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.20",
    maintext: "영상 편집 매니아 여러분! 🎬 영상 편집 스터디 참여하실 분 구합니다. 함께 기술 향상하세요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "디자인 초보자와 함께 공부하는 그룹을 만들어요! 함께 성장해 나가실 분을 찾습니다. 오세요오세요!",
    views: 1500,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "예시 글입니다. 어서와서 같이 코딩 공부합시다! 모집 중입니다. 참여해 주세요.",
    views: 143,
    status: "close",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.06",
    maintext: "프론트엔드 개발 초보자와 함께하는 스터디를 시작합니다. 경력자도 환영합니다!",
    views: 800,
    status: "open",
    like: "unlike",
    popular: false,
    study: false,
  },
  {
    deadline: "2023.12.10",
    maintext: "UI/UX 디자인 스터디 모집합니다. 함께 디자인 실력을 키워봐요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.15",
    maintext: "백엔드 개발자와 함께하는 스터디를 시작합니다. 함께 공부하며 실력을 향상시켜요!",
    views: 600,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2023.12.20",
    maintext: "웹 디자인 초보자와 함께하는 모임입니다. 함께 디자인을 배우고 발전해봐요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.25",
    maintext: "🎉 파이썬 입문자를 환영합니다! 함께하는 Python 초보자 그룹에서 즐거운 학습을 시작해봐요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.31",
    maintext: "🚀 데이터 사이언스 여행에 함께 떠나볼래요? 데이터 분석과 머신러닝을 다루는 스터디를 엽니다!",
    views: 550,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.05",
    maintext: "💡 디자인의 마법에 빠져봐요! UX 디자인 스터디에서 창의적인 디자인을 함께 연마해봐요!",
    views: 800,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2024.01.10",
    maintext: "📝 글쓰기의 기술을 향상시켜보세요! 글쓰기 스터디에서 효과적인 표현력을 함께 키워나갑시다!",
    views: 1100,
    status: "close",
    like: "like",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.15",
    maintext: "💻 코드의 세계로 초대합니다! 프로그래밍 스터디에서 함께 코딩의 매력을 발견해봐요!",
    views: 700,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.20",
    maintext: "🎬 영상 편집의 신세계를 경험하세요! 영상 편집 스터디에서 창의적인 비디오 제작을 배워봐요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.25",
    maintext: "초보자들 모여라! 🚀 Python 스터디 오픈! 기초부터 고수가 되기까지 함께해요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.31",
    maintext: "데이터 사이언스에 빠져봐요! 📊 함께하는 데이터 사이언스 스터디 모집 중! 👩‍💻👨‍💻",
    views: 550,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.05",
    maintext: "디자인 강좌에 눈 돌려봐요! 🎨 웹 디자인 스터디 오픈! 더 나은 UX를 만들기 위해 함께 노력해요!",
    views: 800,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2024.01.10",
    maintext: "글쓰기에 자신 있는 사람 모집! ✍ 글쓰기 스터디에서 함께 발전해요!",
    views: 1100,
    status: "close",
    like: "like",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.15",
    maintext: "코딩 파티에 초대합니다! 💻 프로그래밍 스터디에서 코딩의 신세계를 열어봐요!",
    views: 700,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.20",
    maintext: "영상 편집 매니아 여러분! 🎬 영상 편집 스터디 참여하실 분 구합니다. 함께 기술 향상하세요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "디자인 초보자와 함께 공부하는 그룹을 만들어요! 함께 성장해 나가실 분을 찾습니다. 오세요오세요!",
    views: 1500,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.05",
    maintext: "예시 글입니다. 어서와서 같이 코딩 공부합시다! 모집 중입니다. 참여해 주세요.",
    views: 143,
    status: "close",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.06",
    maintext: "프론트엔드 개발 초보자와 함께하는 스터디를 시작합니다. 경력자도 환영합니다!",
    views: 800,
    status: "open",
    like: "unlike",
    popular: false,
    study: false,
  },
  {
    deadline: "2023.12.10",
    maintext: "UI/UX 디자인 스터디 모집합니다. 함께 디자인 실력을 키워봐요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.15",
    maintext: "백엔드 개발자와 함께하는 스터디를 시작합니다. 함께 공부하며 실력을 향상시켜요!",
    views: 600,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2023.12.20",
    maintext: "웹 디자인 초보자와 함께하는 모임입니다. 함께 디자인을 배우고 발전해봐요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.25",
    maintext: "🎉 파이썬 입문자를 환영합니다! 함께하는 Python 초보자 그룹에서 즐거운 학습을 시작해봐요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.31",
    maintext: "🚀 데이터 사이언스 여행에 함께 떠나볼래요? 데이터 분석과 머신러닝을 다루는 스터디를 엽니다!",
    views: 550,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.05",
    maintext: "💡 디자인의 마법에 빠져봐요! UX 디자인 스터디에서 창의적인 디자인을 함께 연마해봐요!",
    views: 800,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2024.01.10",
    maintext: "📝 글쓰기의 기술을 향상시켜보세요! 글쓰기 스터디에서 효과적인 표현력을 함께 키워나갑시다!",
    views: 1100,
    status: "close",
    like: "like",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.15",
    maintext: "💻 코드의 세계로 초대합니다! 프로그래밍 스터디에서 함께 코딩의 매력을 발견해봐요!",
    views: 700,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.20",
    maintext: "🎬 영상 편집의 신세계를 경험하세요! 영상 편집 스터디에서 창의적인 비디오 제작을 배워봐요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.15",
    maintext: "백엔드 개발자와 함께하는 스터디를 시작합니다. 함께 공부하며 실력을 향상시켜요!",
    views: 600,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2023.12.20",
    maintext: "웹 디자인 초보자와 함께하는 모임입니다. 함께 디자인을 배우고 발전해봐요!",
    views: 950,
    status: "open",
    like: "like",
    popular: true,
    study: false,
  },
  {
    deadline: "2023.12.25",
    maintext: "🎉 파이썬 입문자를 환영합니다! 함께하는 Python 초보자 그룹에서 즐거운 학습을 시작해봐요!",
    views: 1200,
    status: "close",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2023.12.31",
    maintext: "🚀 데이터 사이언스 여행에 함께 떠나볼래요? 데이터 분석과 머신러닝을 다루는 스터디를 엽니다!",
    views: 550,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.05",
    maintext: "💡 디자인의 마법에 빠져봐요! UX 디자인 스터디에서 창의적인 디자인을 함께 연마해봐요!",
    views: 800,
    status: "open",
    like: "like",
    popular: true,
    study: true,
  },
  {
    deadline: "2024.01.10",
    maintext: "📝 글쓰기의 기술을 향상시켜보세요! 글쓰기 스터디에서 효과적인 표현력을 함께 키워나갑시다!",
    views: 1100,
    status: "close",
    like: "like",
    popular: false,
    study: true,
  },
  {
    deadline: "2024.01.15",
    maintext: "💻 코드의 세계로 초대합니다! 프로그래밍 스터디에서 함께 코딩의 매력을 발견해봐요!",
    views: 700,
    status: "open",
    like: "unlike",
    popular: false,
    study: true,
  },
]